regions = {
    "Região Metropolitana de Salvador": [
        "CAMAÇARI, Bahia",
        "CANDEIAS, Bahia",
        "DIAS d'ÁVILA, Bahia",
        # "ITAPARICA, Bahia",
        # "LAURO DE FREITAS, Bahia",
        # "MADRE DE DEUS, Bahia",
        # "MATA DE SÃO JOÃO, Bahia",
        # "POJUCA, Bahia",
        # "SALVADOR, Bahia",
        # "SÃO FRANCISCO DO CONDE, Bahia",
        # "SÃO SEBASTIÃO DO PASSÉ, Bahia",
        # "SIMÕES FILHO, Bahia",
        # "VERA CRUZ, Bahia"
     ],
    # "Centro-Norte Baiano": [
    #     "ABAÍRA, Bahia",
    #     "ÁGUA FRIA, Bahia",
    #     "AMARGOSA, Bahia",
    #     "AMÉLIA RODRIGUES, Bahia",
    #     "ANDARAÍ, Bahia",
    #     "ANGUERA, Bahia",
    #     "ANTÔNIO CARDOSO, Bahia",
    #     "BAIXA GRANDE, Bahia",
    #     "BARRA DA ESTIVA, Bahia",
    #     "BOA VISTA DO TUPIM, Bahia",
    #     "BONINAL, Bahia",
    #     "BONITO, Bahia",
    #     "BREJÕES, Bahia",
    #     "CABACEIRAS DO PARAGUAÇU, Bahia",
    #     "CACHOEIRA, Bahia",
    #     "CAPELA DO ALTO ALEGRE, Bahia",
    #     "CAPIM GROSSO, Bahia",
    #     "CASTRO ALVES, Bahia",
    #     "CONCEIÇÃO DA FEIRA, Bahia",
    #     "CONCEIÇÃO DO ALMEIDA, Bahia",
    #     "CONCEIÇÃO DO JACUÍPE, Bahia",
    #     "CORAÇÃO DE MARIA, Bahia",
    #     "CRAVOLÂNDIA, Bahia",
    #     "CRUZ DAS ALMAS, Bahia",
    #     "DOM MACEDO COSTA, Bahia",
    #     "ELÍSIO MEDRADO, Bahia",
    #     "FEIRA DE SANTANA, Bahia",
    #     "GAVIÃO, Bahia",
    #     "GOVERNADOR MANGABEIRA, Bahia",
    #     "IAÇU, Bahia",
    #     "IBICOARA, Bahia",
    #     "IBIQUERA, Bahia",
    #     "IBITIARA, Bahia",
    #     "IPECAETÁ, Bahia",
    #     "IPIRÁ, Bahia",
    #     "IRAJUBA, Bahia",
    #     "IRAMAIA, Bahia",
    #     "IRAQUARA, Bahia",
    #     "IRARÁ, Bahia",
    #     "ITABERABA, Bahia",
    #     "ITAETÉ, Bahia",
    #     "ITAQUARA, Bahia",
    #     "ITATIM, Bahia",
    #     "ITIRUÇU, Bahia",
    #     "JAGUAQUARA, Bahia",
    #     "JIQUIRIÇÁ, Bahia",
    #     "JUSSIAPE, Bahia",
    #     "LAFAIETE COUTINHO, Bahia",
    #     "LAJE, Bahia",
    #     "LAJEDINHO, Bahia",
    #     "LAJEDO DO TABOCAL, Bahia",
    #     "LENÇÓIS, Bahia",
    #     "MACAJUBA, Bahia",
    #     "MAIRI, Bahia",
    #     "MARACÁS, Bahia",
    #     "MARAGOGIPE, Bahia",
    #     "MARCIONÍLIO SOUZA, Bahia",
    #     "MILAGRES, Bahia",
    #     "MORRO DO CHAPÉU, Bahia",
    #     "MUCUGÊ, Bahia",
    #     "MUNDO NOVO, Bahia",
    #     "MUNIZ FERREIRA, Bahia",
    #     "MURITIBA, Bahia",
    #     "MUTUÍPE, Bahia",
    #     "NAZARÉ, Bahia",
    #     "NOVA FÁTIMA, Bahia",
    #     "NOVA ITARANA, Bahia",
    #     "NOVA REDENÇÃO, Bahia",
    #     "NOVO HORIZONTE, Bahia",
    #     "PALMEIRAS, Bahia",
    #     "PÉ DE SERRA, Bahia",
    #     "PIATÃ, Bahia",
    #     "PINTADAS, Bahia",
    #     "PIRITIBA, Bahia",
    #     "PLANALTINO, Bahia",
    #     "QUIXABEIRA, Bahia",
    #     "RAFAEL JAMBEIRO, Bahia",
    #     "RIACHÃO DO JACUÍPE, Bahia",
    #     "RIO DE CONTAS, Bahia",
    #     "SALINAS DA MARGARIDA, Bahia",
    #     "SANTA BÁRBARA, Bahia",
    #     "SANTA INÊS, Bahia",
    #     "Santa Terezinha, Bahia",
    #     "SANTANÓPOLIS, Bahia",
    #     "SANTO AMARO, Bahia",
    #     "SANTO ANTÔNIO DE JESUS, Bahia",
    #     "SANTO ESTÊVÃO, Bahia",
    #     "SÃO FELIPE, Bahia",
    #     "SÃO FÉLIX, Bahia",
    #     "SÃO GONÇALO DOS CAMPOS, Bahia",
    #     "SÃO JOSÉ DO JACUÍPE, Bahia",
    #     "SÃO MIGUEL DAS MATAS, Bahia",
    #     "SAPEAÇU, Bahia",
    #     "SAUBARA, Bahia",
    #     "SEABRA, Bahia",
    #     "SERRA PRETA, Bahia",
    #     "SOUTO SOARES, Bahia",
    #     "TANQUINHO, Bahia",
    #     "TAPIRAMUTÁ, Bahia",
    #     "TEODORO SAMPAIO, Bahia",
    #     "TERRA NOVA, Bahia",
    #     "UBAÍRA, Bahia",
    #     "UTINGA, Bahia",
    #     "VÁRZEA DA ROÇA, Bahia",
    #     "VÁRZEA DO POÇO, Bahia",
    #     "VARZEDO, Bahia",
    #     "WAGNER, Bahia"
    # ],
    # "Centro-Sul Baiano": [
    #     "AIQUARA, Bahia",
    #     "ANAGÉ, Bahia",
    #     "APUAREMA, Bahia",
    #     "ARACATU, Bahia",
    #     "BARRA DO CHOÇA, Bahia",
    #     "BARRA DO ROCHA, Bahia",
    #     "BELO CAMPO, Bahia",
    #     "BOA NOVA, Bahia",
    #     "BOM JESUS DA SERRA, Bahia",
    #     "BRUMADO, Bahia",
    #     "CAATIBA, Bahia",
    #     "CACULÉ, Bahia",
    #     "CAETANOS, Bahia",
    #     "CAETITÉ, Bahia",
    #     "CANDIBA, Bahia",
    #     "CÂNDIDO SALES, Bahia",
    #     "CARAÍBAS, Bahia",
    #     "CONDEÚBA, Bahia",
    #     "CONTENDAS DO SINCORÁ, Bahia",
    #     "CORDEIROS, Bahia",
    #     "DÁRIO MEIRA, Bahia",
    #     "DOM BASÍLIO, Bahia",
    #     "ENCRUZILHADA, Bahia",
    #     "FIRMINO ALVES, Bahia",
    #     "GONGOGI, Bahia",
    #     "GUAJERU, Bahia",
    #     "GUANAMBI, Bahia",
    #     "IBIASSUCÊ, Bahia",
    #     "IBICUÍ, Bahia",
    #     "IBIRATAIA, Bahia",
    #     "IGUAÍ, Bahia",
    #     "IPIAÚ, Bahia",
    #     "ITAGI, Bahia",
    #     "ITAGIBÁ, Bahia",
    #     "ITAMARI, Bahia",
    #     "ITAMBÉ, Bahia",
    #     "ITAPETINGA, Bahia",
    #     "ITARANTIM, Bahia",
    #     "ITORORÓ, Bahia",
    #     "ITUAÇU, Bahia",
    #     "IUIU, Bahia",
    #     "JACARACI, Bahia",
    #     "JEQUIÉ, Bahia",
    #     "JITAÚNA, Bahia",
    #     "LAGOA REAL, Bahia",
    #     "LICÍNIO DE ALMEIDA, Bahia",
    #     "LIVRAMENTO DE NOSSA SENHORA, Bahia",
    #     "MACARANI, Bahia",
    #     "MAETINGA, Bahia",
    #     "MAIQUINIQUE, Bahia",
    #     "MALHADA DE PEDRAS, Bahia",
    #     "MANOEL VITORINO, Bahia",
    #     "MIRANTE, Bahia",
    #     "MORTUGABA, Bahia",
    #     "NOVA CANAÃ, Bahia",
    #     "NOVA IBIÁ, Bahia",
    #     "PALMAS DE MONTE ALTO, Bahia"
    # ],
}